version: "3.8"
services:
    wordpress:
        container_name: wordpress
        image: wordpress:php7.4-apache
        restart: always
        stdin_open: true
        tty: true
        environment:
            WORDPRESS_DB_HOST: CLOUDSQL_IP
            WORDPRESS_DB_USER: database_user
            WORDPRESS_DB_PASSWORD: database_user_password
            WORDPRESS_DB_NAME: database_name
        volumes:
            - ./wordpress:/var/www/html
       
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
